nop:
  extension:
    undertow:
      server:
        port: 8075
        host: 127.0.0.1
        compression:
          # 启用压缩支持，提升页面加载速度
          enabled: true
          # minResponseSize: 2048
          mime-types: text/html,text/xml,text/plain,text/javascript,text/css,image/svg+xml,application/json,application/xml,application/javascript,application/x-shockwave-flash
