# Singleton service factory configuration/IoC injection
singletons:
  # HandlerProvider implementation
  - com.networknt.handler.HandlerProvider:

  # StartupHookProvider implementations, there are one to many and they are called in the same sequence defined.
  - com.networknt.server.StartupHookProvider:
      - io.crazydan.duzhou.framework.starter.service.Light4jInitializer

    # ShutdownHookProvider implementations, there are one to many and they are called in the same sequence defined.
  - com.networknt.server.ShutdownHookProvider:
      - io.crazydan.duzhou.framework.starter.service.Light4jInitializer

  # MiddlewareHandler implementations, the calling sequence is as defined in the request/response chain.
  - com.networknt.handler.MiddlewareHandler:
