duzhou:
  gateway:
    web:
      static-resources:
        # 在开发阶段，Web 静态资源直接指向前端 web 项目下的构建资源目录
        path: "file:${project.basedir}/../../../frontend/web/dist"

nop:
  debug: true
  profile: dev
  orm:
    init-database-schema: true
  datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:./db/duzhou
    username: sa
    password:
  file:
    store-dir: "${project.build.directory}/files"
