nop:
  debug: true
  orm:
    init-database-schema: true
  datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:./db/duzhou-app
    username: sa
    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    jdbc-url: jdbc:mysql://127.0.0.1:3306/dev?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    username: nop
#    password: nop-test
  file:
    # 可选值: local, oss
    store-impl: local
    store-dir: "${project.build.directory}/files"
  integration:
    # MinIO 容器部署文档: https://min.io/docs/minio/container/operations/install-deploy-manage/deploy-minio-single-node-single-drive.html#minio-snsd
    oss:
      enabled: true
      access-key: user
      secret-key: password
      # MinIO 的 API 地址
      endpoint: http://172.17.0.1:9512
      # Bucket 可以在 MinIO 的控制台页面进行创建
      default-bucket-name: default
      # 阿里云要求 pathStyleAccess 必须设置为 false
      #path-style-access: false

# 支持graphql __schema查询，
  graphql:
    schema-introspection:
      enabled: true

# devservices 会启用testcontainers来管理测试数据库
quarkus:
  devservices:
    enabled: false

  datasource:
    devservices:
      enabled: false

  http:
    host: 0.0.0.0
    cors: false

  log:
    level: INFO

    category:
      "io.nop":
        level: INFO
